### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by jon4hz** [TheYahya/enola#10]
Hi, I think enola is returning false positives. 
When I check my username with `sherlock`, I get 18 results. However when I use `enola`, I get 49.

**Comment by darkknight443** [comment]
don't they use the same data?

**Comment by TheYahya** [comment]
the database is almost the same. 

I will check, But let me know if you're aware of any specific false positive items.

**Comment by jon4hz** [comment]
well, there are at least 31 sites which returned different results.
Among them are mixcloud, twitch and freecodecamp (to name a few). 
If you want the full list, just compare the results from sherlock and enola with my username (jon4hz)

**Comment by bryceprutsos** [comment]
Yeah just came here to let you know about the false positives. It seems like sites that have automatic 404 user not found.

**Comment by pure-blue** [comment]
Yeah, just downloaded enola for the first time and while it's absolutely gorgeous visually, I'm getting three pages of positive hits, but every link that I've clicked on (aside from the one I know to be real) either goes to a 404 page or if the page does load, there simply isn't an actual user with that username on the site. So as things stand this doesn't seem to be working at all.

**Comment by jon4hz** [comment]
dccdd
