### ISSUE TITLE
possibility to return available usernames?

### ISSUE THREAD

**Issue by dpthegrey** [TheYahya/enola#17]
I have a platform which i am looking for any available username under x amount characters, I do not know which one is available anything nice and short i come up to is already taken. 

I was wondering if we can build up on this to get potential available usernames, either a word or random characters as username by not overwhelming the server with keeping rate limitations in mind based on website

**Comment by TheYahya** [comment]
Hi @dpthegrey, 

I think thanks possible, Hard to predict/know all the websites' rate limitations though!
