### ISSUE TITLE
False negative found

### ISSUE THREAD

**Issue by edoardottt** [TheYahya/enola#19]
Hi @TheYahya and thanks for this project.

I've just installed the tool with (0.1.3)
```
go install github.com/theyahya/enola/cmd/enola@latest
```

and tried with my username (edoardottt).

I see that Youtube User and Youtube channel say not found, while I have a YT channel.

In data.json I see:
```
"Youtube Channel": {
    "errorType": "status_code",
    "errorCode": 404,
    "headers": {
      "Cookie": "CONSENT=YES+cb.20210418-17-p0.it+FX+917; "
    },
    "url": "https://www.youtube.com/c/{}",
    "urlMain": "https://www.youtube.com",
    "username_claimed": "mkbhd",
    "username_unclaimed": "noonewouldeverusethis7"
  },
  "Youtube User": {
    "errorType": "status_code",
    "errorCode": 404,
    "headers": {
      "Cookie": "CONSENT=YES+cb.20210418-17-p0.it+FX+917; "
    },
    "url": "https://www.youtube.com/user/{}",
    "urlMain": "https://www.youtube.com",
    "username_claimed": "pewdiepie",
    "username_unclaimed": "noonewouldeverusethis7"
  }
```
I think that YT channel URL format is the old one, now it's like this: https://www.youtube.com/@edoardottt.

I don't know why it says that the user is not present since I'm on youtube with the username edoardottt... idk

**Comment by amirrossein** [comment]
I guess Youtube recently introduced Youtube handles that you can assign to your channel with "@".
@TheYahya This is an odd one, the username_claimed for both the Youtube channel and users are working properly, but these methods are not working for `edoardottt`, instead the `edoardottt` is working like https://www.youtube.com/@edoardottt.
I think we need to create a third method called "Youtube Handle" to deal with this kind.

**Comment by TheYahya** [comment]
@amirrossein 
A PR will be appreciated.
